// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBeMydSHyaJ0NTBGPM4l3ihtEcMbMjeh4',
    appId: '1:138915213389:web:6ab32589e2bc08c859ec04',
    messagingSenderId: '138915213389',
    projectId: 'orthoscan-cc568',
    authDomain: 'orthoscan-cc568.firebaseapp.com',
    storageBucket: 'orthoscan-cc568.appspot.com',
    measurementId: 'G-JM7EZ23D88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpm3h0go4DX_h8xH4-FdjRHdpX4N6JS78',
    appId: '1:138915213389:android:93831971158649a159ec04',
    messagingSenderId: '138915213389',
    projectId: 'orthoscan-cc568',
    storageBucket: 'orthoscan-cc568.appspot.com',
  );
}
